#!/bin/sh
# References
# http://labs.infyom.com/laravelgenerator/
# http://www.initializr.com/
# https://laravel.com/
# https://cdnjs.com/
# https://necolas.github.io/normalize.css/
# https://leaverou.github.io/prefixfree/
# https://jquery.com/

red="\033[0;31m"
gre="\033[0;32m"
yel="\033[0;33m"
nor="\033[0m"

fresh(){
# echo "$yel""\nRemoving the .git of Admin LTE from the foulder."
# rm -rf .git

echo "Running: npm install$nor"
composer install
npm install

echo "$yel""Changing the web.php file."
sed -i '14,$d' routes/web.php
echo "Route::get('/', function () {
  return view('pages.home');
});

Auth::routes();

Route::get('/admin', 'AdminController@index');" >> routes/web.php

echo "Deleting HomeController.php."
rm -rf app/Http/Controllers/HomeController.php

echo "Creating AdminController.php."
echo "<?php

namespace App\Http\Controllers;

class AdminController extends Controller
{
    public function __construct()
    {
        \$this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pages.admin');
    }
}" >> app/Http/Controllers/AdminController.php

echo "Changing Login, Register and Password Controllers."
sed -i -- 's/home/pages.admin/g' app/Http/Controllers/Auth/LoginController.php
sed -i -- 's/home/pages.admin/g' app/Http/Controllers/Auth/RegisterController.php
sed -i -- 's/home/pages.admin/g' app/Http/Controllers/Auth/ResetPasswordController.php

echo "Creating the pages foulder."
mkdir resources/views/pages

echo "Renaming the home.blade.php view to admin.blade.php."
mv resources/views/home.blade.php resources/views/pages/admin.blade.php

echo "Deleting the welcome.blade.php view."
rm -rf resources/views/welcome.blade.php

echo "Creating the layout-home foulder."
mkdir resources/views/layout-home

# Master
echo "Creating the master.blade.php layout."
echo "<!DOCTYPE html>
<html lang=\"{{ app()->getLocale() }}\">
    @include('layout-home.head')

    <body>
    	@include('layout-home.nav')

		@yield('content')

        @include('layout-home.footer')

        @include('layout-home.scripts')	
    </body>
</html>" >> resources/views/layout-home/master.blade.php

# Head
echo "Creating the head.blade.php layout."
echo "<head>
    <meta charset=\"utf-8\">
    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">
    <title></title>
    <meta name=\"description\" content=\"\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
    <meta name=\"csrf-token\" content=\"{{ csrf_token() }}\">
    <link rel=\"icon\" type=\"image/png\" href=\"\">

    <!-- Fonts -->

    <!-- Normalize CDN -->
    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css\" integrity=\"sha256-HxaKz5E/eBbvhGMNwhWRPrAR9i/lG1JeT4mD6hCQ7s4=\" crossorigin=\"anonymous\">

    <!-- CSS/SASS -->
    <link rel=\"stylesheet\" href=\"/css/home.css\">
</head>" >> resources/views/layout-home/head.blade.php

# Nav
echo "Creating the nav.blade.php layout."
echo "<nav>

</nav>" >> resources/views/layout-home/nav.blade.php

# Footer
echo "Creating the footer.blade.php layout."
echo "<footer>

</footer>" >> resources/views/layout-home/footer.blade.php

# Scripts
echo "Creating the scripts.blade.php layout."
echo "<!-- JQuery CDN -->
<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\" integrity=\"sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=\" crossorigin=\"anonymous\"></script>

<!-- Prefixfree CDN -->
<script src=\"https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js\" integrity=\"sha256-GaKOLXTn7uJXFuWp57ukQZGuKK2gWZWlEH16hc6jBU8=\" crossorigin=\"anonymous\"></script>

<!-- Javascript -->
<script type=\"text/javascript\" src=\"/js/home.js\"></script>" >> resources/views/layout-home/scripts.blade.php

# Home Page
echo "Creating the home.blade.php page."
echo "@extends('layout-home.master')

@section('content')

@endsection" >> resources/views/pages/home.blade.php

echo "Populating webpack.mix.js file whit the home.js and home.scss files."
sed -i '14,$d' webpack.mix.js
echo "mix.js('resources/assets/js/app.js', 'public/js')
   .js('resources/assets/js/home.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
   .sass('resources/assets/sass/home.scss', 'public/css');" >> webpack.mix.js

echo "Creating the home.js file."
echo "// Custom Javascript
" >> resources/assets/js/home.js

echo "Populating the home.scss file whit the home page layouts."
echo "/* Fonts */

/* Variables */
@import \"home-variables\";
/* Home Nav */
@import \"home-nav\";
/* Home Body */
@import \"home-body\";
/* Home Footer */
@import \"home-footer\";
" >> resources/assets/sass/home.scss

echo "Creating the _home-variables, _home-nav, _home-body and _home-footer SASS files."
echo "/* Home Variables */
" >> resources/assets/sass/_home-variables.scss
echo "/* Home Nav */
" >> resources/assets/sass/_home-nav.scss
echo "/* Home Body */
" >> resources/assets/sass/_home-body.scss
echo "/* Home Footer */
" >> resources/assets/sass/_home-footer.scss

echo "Compiling the JS and SASS files."
npm run dev

echo "$gre""\nDone!
After you create a db and a .env file, run:$nor
php artisan migrate
php artisan key:generate$gre
Run$nor composer install$gre to resolve the dependencies.
Run$nor npm run watch$gre to compile the SASS in real time."
} # END fresh

echo "$nor""Generating the template for InfyOm Laravel Generator/AdminLTE integrated whit front-end on Laravel 5.4 project."
echo "Created by""$yel Grupo Tesseract$nor"".\n"

echo "$gre""Make sure you followed these steps before running the program:" 
echo "$yel""Cloned InfyOm Laravel Generator for AdminLTE Template:"
echo "$nor""git clone https://github.com/InfyOmLabs/adminlte-generator.git project-name"
echo "Be in the project directory.\n"

echo -n "$nor""Have you followed those steps?$gre [y|n]$nor"": "; read input_variable
case $input_variable in
	'y')
	    fresh
	    ;;
	'n')
	    echo "$red""Canceling the action.$nor"
		;;
	'')
	    echo "$red""No arguments detected!$nor"
		;;
	*)
		echo "$red""Invalid argument!$nor"
		;;
esac